name: Iperf3 Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the iperf3 image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)